### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by lmguzman** [UBC-MDS/prepackR#13]
This project is very well done and set up. You did a terrific job setting up the package. 

Here are a few comments that you can improve upon:

- Modify your description file so it reflects you as the creators. 

- Functions:
   - Add a dummy output to your function.
   - In splitter, @param target_index numeric is not very clear what it means. The description you had in the readme is much better, but looking just at the help file I wouldn’t know what this means. 

- Tests
   - Test_splitter is very well done. Make sure you also add tests for the output
   - For test_stdizer and test_na_counter make sure that you give meaningful error messages.

**Comment by smwatts** [comment]
**Comment 1:**
We will modify our description file so it reflects us as the creators in milestone 3 (as part of our R submission)

**Comment 2:**
We will add output to our functions and improve our descriptions for the splitter function in milestone 3 (as part of our R submission)

**Comment 3:**
For our python repo:
Improved documentation in the tests for test_stdizer here: https://github.com/UBC-MDS/prepackPy/pull/25
Improved documentation in the tests for test_na_counter here: https://github.com/UBC-MDS/prepackPy/pull/26

We will improve our documentation in our R repo as part of milestone 3.
